spring:
    datasource:
        url: jdbc:mysql://localhost:3306/elakatos
        username: user
        password: userpw
        driver-class-name: com.mysql.cj.jdbc.Driver
    jpa:
        hibernate:
            ddl-auto: update
        open-in-view: false
jwt:
    secret: my-very-long-secret-key-with-at-least-32-characters
    expiration: 1800000