spring:
    datasource:
        url: jdbc:mysql://localhost:3306/elakatos
        username: user
        password: userpw
        driver-class-name: com.mysql.cj.jdbc.Driver
    jpa:
        hibernate:
            ddl-auto: update
        open-in-view: false
jwt:
    secret: bce4c6d1e91aa1f9eea528b5e37f38bd
    expiration: 1800000